# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 16:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171211_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bid_end_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 16, 52, 58, 620560)),
        ),
    ]
